version: '3.7'
services:
    web:
        build: ./Dockerfile-backend
        ports:
            - "80:5000"
        volumes:
            - ./backend:/backend
        environment:
            - DB=mongodb://mongodb:27017/snakeDatabase
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db/:/data/db
        ports:
            - 27017:27017
        command: mongod